# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: goreleaser-example

builds:
  - binary: goreleaser-example
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
      - riscv64
    ignore:
      - goos: windows
        goarch: riscv64
    # ensures mod timestamp to be the commit timestamp
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      # trims path
      - -trimpath
    ldflags:
      # use commit date instead of current date as main.date
      # only needed if you actually use those things in your main package, otherwise can be ignored.
      - -s
      - -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{ .CommitDate }}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{- .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}armhf
      {{- else if eq .Arch "arm64" }}arm64v8
      {{- else if eq .Arch "riscv64" }}riscv64
      {{- else }}{{ .Arch }}{{ end }}_
      {{- .Version -}}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE

dockers:
  - # linux/amd64
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/nicholas-fedor/{{ .ProjectName }}:amd64-{{ .Version }}
      - ghcr.io/nicholas-fedor/{{ .ProjectName }}:amd64-latest
    dockerfile: Dockerfile
    use: buildx
    skip_push: false # Ensure individual images are pushed
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/nicholas-fedor/{{ .ProjectName }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
      - --attest=type=provenance,mode=max
      - --attest=type=sbom
  - # linux/i386
    goos: linux
    goarch: "386"
    image_templates:
      - ghcr.io/nicholas-fedor/{{ .ProjectName }}:i386-{{ .Version }}
      - ghcr.io/nicholas-fedor/{{ .ProjectName }}:i386-latest
    dockerfile: Dockerfile
    use: buildx
    skip_push: false # Ensure individual images are pushed
    build_flag_templates:
      - --platform=linux/386
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/nicholas-fedor/{{ .ProjectName }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
      - --attest=type=provenance,mode=max
      - --attest=type=sbom
  - # linux/armhf
    goos: linux
    goarch: arm
    goarm: "6"
    image_templates:
      - ghcr.io/nicholas-fedor/{{ .ProjectName }}:armhf-{{ .Version }}
      - ghcr.io/nicholas-fedor/{{ .ProjectName }}:armhf-latest
    dockerfile: Dockerfile
    use: buildx
    skip_push: false # Ensure individual images are pushed
    build_flag_templates:
      - --platform=linux/arm/v6
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/nicholas-fedor/{{ .ProjectName }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
      - --attest=type=provenance,mode=max
      - --attest=type=sbom
  - # linux/arm64v8
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/nicholas-fedor/{{ .ProjectName }}:arm64v8-{{ .Version }}
      - ghcr.io/nicholas-fedor/{{ .ProjectName }}:arm64v8-latest
    dockerfile: Dockerfile
    use: buildx
    skip_push: false # Ensure individual images are pushed
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/nicholas-fedor/{{ .ProjectName }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
      - --attest=type=provenance,mode=max
      - --attest=type=sbom
  - # linux/riscv64
    goos: linux
    goarch: riscv64
    image_templates:
      - ghcr.io/nicholas-fedor/{{ .ProjectName }}:riscv64-{{ .Version }}
      - ghcr.io/nicholas-fedor/{{ .ProjectName }}:riscv64-latest
    dockerfile: Dockerfile
    use: buildx
    skip_push: false # Ensure individual images are pushed
    build_flag_templates:
      - --platform=linux/riscv64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/nicholas-fedor/{{ .ProjectName }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
      - --attest=type=provenance,mode=max
      - --attest=type=sbom

changelog:
  sort: asc
  filters:
    include:
      - "^feat"
      - "^fix"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

checksum:
  name_template: "checksums.txt"

sboms:
  - artifacts: archive
