name: Build Release

on:
  workflow_call:

jobs:
  # Build binaries, images, SBOMs, and attestations for production or development
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    permissions:
      contents: write # For code checkout and publishing releases
      packages: write # For pushing images to registries
      attestations: write # For generating provenance and SBOMs
      id-token: write # For OIDC auth to container registry
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0 # Full history for GoReleaser versioning.

      - name: Set up Go
        uses: actions/setup-go@8e57b58e57be52ac95949151e2777ffda8501267
        with:
          go-version: 1.25.x

      - name: Set up QEMU # Enable multi-platform emulation.
        uses: docker/setup-qemu-action@05340d1c670183e7caabdb33ae9f1c80fae3b0c2
        with:
          platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm64/v8,linux/riscv64

      - name: Set up Docker Buildx # Configure multi-platform builds.
        uses: docker/setup-buildx-action@af1b253b8dc984466d22633f04ef341c1520ed2f
        with:
          driver: docker-container
          platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm64/v8,linux/riscv64
          use: true

      - name: Enable containerd snapshotter # Enable containerd for multi-platform builds
        run: |
          sudo bash -c 'echo "{\"features\": {\"containerd-snapshotter\": true}}" > /etc/docker/daemon.json'
          sudo systemctl restart docker

      - name: Install Syft for SBOM generation # Install Syft for GoReleaser SBOM generation
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Login to GHCR # Authenticate to GHCR
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload binary SBOMs # Upload SBOMs for prod builds.
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: binary-sboms
          path: ./dist/*.sbom.json
          if-no-files-found: warn

      - name: Generate artifact attestation # Generate attestations for prod builds.
        uses: actions/attest-build-provenance@f0878de78276446bc2ff4a40ae81f8013db6d773
        with:
          subject-checksums: ./dist/checksums.txt

      - name: Clean up dist directory # Remove dist directory to avoid leftover artifacts.
        if: always()
        run: rm -rf dist
